# Generated by Django 5.0.3 on 2024-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_featuredproduct_topproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
