# Generated by Django 5.0.3 on 2024-04-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_personinfo_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('class_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonInfo',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.school'),
        ),
    ]
