# Generated by Django 5.0.3 on 2024-07-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_author_musician_rubric_stuff_advuser_authorprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.newarrivals')),
            ],
        ),
    ]
