# Generated by Django 5.0.3 on 2024-04-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_personalinfo_delete_personinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=30)),
                ('stuff_desc', models.CharField(max_length=257)),
                ('photo', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Musicion',
            new_name='Musician',
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='class_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('items', models.ManyToManyField(to='market.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.person')),
            ],
        ),
    ]
