# Generated by Django 5.0.3 on 2024-05-03 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_album_num_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('student_card_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('meeting_room', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(choices=[('A', 'Alexander'), ('B', 'Rimma'), ('C', 'Oleg'), ('D', 'Timofey')], max_length=1),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(choices=[('A', 'Alexander'), ('B', 'Rimma'), ('C', 'Oleg'), ('D', 'Timofey')], max_length=1),
        ),
        migrations.CreateModel(
            name='BookBorrowingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_date', models.DateField()),
                ('giver_name', models.CharField(max_length=200)),
                ('library_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.librarycard')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.libraryliterature')),
            ],
        ),
        migrations.AddField(
            model_name='librarycard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.student'),
        ),
    ]
