# Generated by Django 5.0.3 on 2024-05-11 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_librarycard_libraryliterature_student_studentgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoITeeens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
