# Generated by Django 5.0.3 on 2024-05-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_goiteeens'),
    ]

    operations = [
        migrations.AddField(
            model_name='goiteeens',
            name='kind',
            field=models.CharField(choices=[('A', 'Buy'), ('A', 'Sell'), ('A', 'Change')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='goiteeens',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
