# Generated by Django 5.0.3 on 2024-05-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_goiteeens_kind_alter_goiteeens_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goiteeens',
            name='kind',
            field=models.CharField(choices=[(None, 'Choose'), ('b', 'Buy'), ('s', 'Sell'), ('с', 'Change'), ('r', 'Rent')], default='s', max_length=1),
        ),
    ]
