# Generated by Django 5.0.3 on 2024-05-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_goiteeens_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoITeeens',
        ),
    ]
