from django.contrib import admin
from .models import Musician, Album, Person, School, Class, PersonalInfo, Stuff, Category, Product, UserProfile, Order, OrderItem, Student, StudentGroup, LibraryCard, LibraryLiterature, BookBorrowingProcess

admin.site.register(Musician)
admin.site.register(Album)
admin.site.register(Person)
admin.site.register(School)
admin.site.register(Class)
admin.site.register(PersonalInfo)
admin.site.register(Stuff)
admin.site.register(Category)
admin.site.register(Product)
admin.site.register(UserProfile)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Student)
admin.site.register(StudentGroup)
admin.site.register(LibraryCard)
admin.site.register(LibraryLiterature)
admin.site.register(BookBorrowingProcess)